language: rust

rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
after_success:
  - travis-cargo --only nightly doc-upload
env:
  global:
    - secure: "aCzki4/6x0CAkTBpftjKCEuSmQHa0nQSvIQOAYJXBx3YgRPeDcTWs9MVfLn5h+6sMfANsakmhlBz6yzlieGKhGT9AlURBIn1mdxjrkYCXVqh/SndaGMW4JAuhwqcJp1DzRTZI50xfRK57yiN4XOFGiEjtn4ienqx2AbRXpHeKYCIQ85fCDYNiFsccAtvx6S9TC357dS9zRYRWvtACEqqtuEB3piz6T6bxs8x+Pgqd9IOQPDI9seZuGwKCi4psb3QTyVnUswz4gL5h0aajj/zxuFqVS2q0kNGqiTuAP05Y3w49VYWHSLMCH0estNuuJaCwJ4pQSlkoPvBFJzdAbOHrIbJoAM0qJxOjrQiCq2T/GMHBVBdMkOXNQjyplGkUYGFPBLSOPLUDJZSPYNgUZnYNU4dVUiJabvSUYMkdxsp3W9fZQV5NaoOhUUumm6N7/YI/xED/biF2Tj5pgPNKDQ/EZUF5DaL3LK653WpN3q4aTvQZdO6RhSRQoW5mZkBZemb/1cnuwj1dGaIP/+yI7WrxiyCET5ZgwVkLHfWSK/6gJykLDD5k+qyF6j0qluiV6IAZA/xQfdpeXyq9Y46jNuHtPu7Mtrx5bB0QkT+wOckbd8im3gJTT12R7W2K3ETjs3ImUQKDehBBDwJetkz7k0zUiodeITXnK/pirOJf3LmXqk="

notifications:
  email:
    on_success: never
