language: rust

rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
after_success:
  - travis-cargo --only nightly doc-upload
env:
  global:
    - secure: L1pFJlWEev8ClRj9EgOFALQqVVG9MXBOP0tT09fqS13IikVcgZZ7lz5R7vL/wNQEqO+NCA3woAVlsYSkKEM3/btME/aPk0Kq8azueDlslZdsCqcNzr3cUqxGy6BY6IYlPZYI6zFFDE9ApKvyeoHUTgF3CIJNmFQkj5h/iWLqeOJ50/WEemiUaTj56hRBCGKXGR5QxWKE2u4UxtGCDcpqjgiy6qawymtP/mUPoNmeuSRvUphtnaav6+Ck0kpKkLzKi70lpzP45KYRjxYJkAGbh5nO7WmRdkRCJfhKw+3oWDrvitVfxZUW50WjWrFD0uhdkCJT4BpUFF1Pvr8SMlbCDYMs6UqRJ/cl9x+x7Q7iqAeQdTNHLhb9Iihy9oJvtMKtA69kJk2qkVK4jVCyvoJR7vrU4VWPf1KYIXqv8QZw23RPessg+ns1/0URS2g59XCPc13Z9Yf0B9uKSjGsF5Gi0qM2dtEwi9BjftSFbYsIESJl1QoCi+5Do57PF1F7XSdroGDc22lt3iAVUjfvB+cDh5/aEJnTS35FyHbRpGHdU3IjvPm6k9MfQnsgxqLMCWB78mcAvSewx2dKbgNZ7A4/H3JEkHE1hP+SXyExlMRvXj9pAFXWCDgagfx+teCnXjjKVJwp7hONtqviINVFCwtHHuJDc+qIiIC80nON5+sdCfk=
notifications:
  email:
    on_success: never
